"""add field total_price

Revision ID: d940ffd10893
Revises: 218e07eb5602
Create Date: 2023-11-26 16:39:43.603259

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d940ffd10893"
down_revision: Union[str, None] = "218e07eb5602"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hotels", sa.Column("total_price", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotels", "total_price")
    # ### end Alembic commands ###
