"""add colomn caption

Revision ID: 4f250c2875c1
Revises: fb73414329e6
Create Date: 2023-11-24 18:58:39.785275

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4f250c2875c1'
down_revision: Union[str, None] = 'fb73414329e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('caption', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'caption')
    # ### end Alembic commands ###
