"""create_table

Revision ID: 47e493ef653e
Revises: 
Create Date: 2023-11-27 22:01:21.502106

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '47e493ef653e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_chat_id', sa.Integer(), nullable=False),
                    sa.Column('command', sa.String(length=20), nullable=False),
                    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('hotels',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('address', sa.String(length=300), nullable=False),
                    sa.Column('hotel_name', sa.String(length=300), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('request_id', sa.Integer(), nullable=False),
                    sa.Column('distance', sa.Float(), nullable=False),
                    sa.Column('total_price', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_hotels_request_id'), 'hotels', ['request_id'], unique=False)
    op.create_table('images',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('image_url', sa.String(length=200), nullable=False),
                    sa.Column('hotel_id', sa.Integer(), nullable=False),
                    sa.Column('caption', sa.String(length=100), nullable=True),
                    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_images_hotel_id'), 'images', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_hotel_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_hotels_request_id'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_table('requests')
    # ### end Alembic commands ###
